// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbequimwiuzbltaiftrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZXF1aW13aXV6Ymx0YWlmdHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzI1MTMsImV4cCI6MjA3MzYwODUxM30.DLdkcAwo4EN4wH1nVHJKJuNj0UDfcwHKSqKgXvDCn0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});